// Centralized config key names grouped by domain

export const gyroBehaviorKeys = [
  'GYRO_SPACE',
  'GYRO_AXIS_X',
  'GYRO_AXIS_Y',
  'TICK_TIME',
  'IGNORE_GYRO_DEVICES',
  'COUNTER_OS_MOUSE_SPEED',
] as const

export const noiseKeys = [
  'GYRO_CUTOFF_SPEED',
  'GYRO_CUTOFF_RECOVERY',
  'GYRO_SMOOTH_TIME',
  'GYRO_SMOOTH_THRESHOLD',
  'GYRO_ANGLE_SNAP',
] as const

export const sensitivityKeys = [
  'GYRO_SENS',
  'MIN_GYRO_SENS',
  'MAX_GYRO_SENS',
  'MIN_GYRO_THRESHOLD',
  'MAX_GYRO_THRESHOLD',
  'ACCEL_CURVE',
  'ACCEL_NATURAL_VHALF',
  'ACCEL_POWER_VREF',
  'ACCEL_POWER_EXPONENT',
  'ACCEL_SIGMOID_MID',
  'ACCEL_SIGMOID_WIDTH',
  'ACCEL_JUMP_TAU',
  'IN_GAME_SENS',
  'REAL_WORLD_CALIBRATION',
] as const

export const timingKeys = [
  'HOLD_PRESS_TIME',
  'DBL_PRESS_WINDOW',
  'SIM_PRESS_WINDOW',
  'TRIGGER_THRESHOLD',
] as const

export const touchpadKeys = ['TOUCHPAD_MODE', 'GRID_SIZE', 'TOUCHPAD_SENS'] as const

export const stickKeys = [
  'STICK_DEADZONE_INNER',
  'STICK_DEADZONE_OUTER',
  'LEFT_STICK_DEADZONE_INNER',
  'LEFT_STICK_DEADZONE_OUTER',
  'RIGHT_STICK_DEADZONE_INNER',
  'RIGHT_STICK_DEADZONE_OUTER',
  'LEFT_STICK_MODE',
  'RIGHT_STICK_MODE',
  'LEFT_RING_MODE',
  'RIGHT_RING_MODE',
  'STICK_SENS',
  'STICK_POWER',
  'STICK_ACCELERATION_RATE',
  'STICK_ACCELERATION_CAP',
  'FLICK_TIME',
  'FLICK_TIME_EXPONENT',
  'FLICK_SNAP_MODE',
  'FLICK_SNAP_STRENGTH',
  'FLICK_DEADZONE_ANGLE',
  'MOUSE_RING_RADIUS',
  'SCROLL_SENS',
] as const

export const bindingSpecialKeys = [
  'GYRO_OFF',
  'GYRO_ON',
  'GYRO_OFF_ALL',
  'GYRO_ON_ALL',
  'GYRO_INVERT',
  'GYRO_INV_X',
  'GYRO_INV_Y',
  'GYRO_TRACKBALL',
  'GYRO_TRACK_X',
  'GYRO_TRACK_Y',
] as const

export type GyroBehaviorKey = typeof gyroBehaviorKeys[number]
export type NoiseKey = typeof noiseKeys[number]
export type SensitivityKey = typeof sensitivityKeys[number]
export type TimingKey = typeof timingKeys[number]
export type TouchpadKey = typeof touchpadKeys[number]
export type StickKey = typeof stickKeys[number]
export type BindingSpecialKey = typeof bindingSpecialKeys[number]

// Flat key name map for convenient imports
export const keyName = {
  // Gyro behavior
  GYRO_SPACE: 'GYRO_SPACE',
  GYRO_AXIS_X: 'GYRO_AXIS_X',
  GYRO_AXIS_Y: 'GYRO_AXIS_Y',
  TICK_TIME: 'TICK_TIME',
  IGNORE_GYRO_DEVICES: 'IGNORE_GYRO_DEVICES',
  COUNTER_OS_MOUSE_SPEED: 'COUNTER_OS_MOUSE_SPEED',

  // Noise
  GYRO_CUTOFF_SPEED: 'GYRO_CUTOFF_SPEED',
  GYRO_CUTOFF_RECOVERY: 'GYRO_CUTOFF_RECOVERY',
  GYRO_SMOOTH_TIME: 'GYRO_SMOOTH_TIME',
  GYRO_SMOOTH_THRESHOLD: 'GYRO_SMOOTH_THRESHOLD',
  GYRO_ANGLE_SNAP: 'GYRO_ANGLE_SNAP',

  // Sensitivity
  GYRO_SENS: 'GYRO_SENS',
  MIN_GYRO_SENS: 'MIN_GYRO_SENS',
  MAX_GYRO_SENS: 'MAX_GYRO_SENS',
  MIN_GYRO_THRESHOLD: 'MIN_GYRO_THRESHOLD',
  MAX_GYRO_THRESHOLD: 'MAX_GYRO_THRESHOLD',
  ACCEL_CURVE: 'ACCEL_CURVE',
  ACCEL_NATURAL_VHALF: 'ACCEL_NATURAL_VHALF',
  ACCEL_POWER_VREF: 'ACCEL_POWER_VREF',
  ACCEL_POWER_EXPONENT: 'ACCEL_POWER_EXPONENT',
  ACCEL_SIGMOID_MID: 'ACCEL_SIGMOID_MID',
  ACCEL_SIGMOID_WIDTH: 'ACCEL_SIGMOID_WIDTH',
  ACCEL_JUMP_TAU: 'ACCEL_JUMP_TAU',
  IN_GAME_SENS: 'IN_GAME_SENS',
  REAL_WORLD_CALIBRATION: 'REAL_WORLD_CALIBRATION',

  // Timing / thresholds
  HOLD_PRESS_TIME: 'HOLD_PRESS_TIME',
  DBL_PRESS_WINDOW: 'DBL_PRESS_WINDOW',
  SIM_PRESS_WINDOW: 'SIM_PRESS_WINDOW',
  TRIGGER_THRESHOLD: 'TRIGGER_THRESHOLD',

  // Touchpad
  TOUCHPAD_MODE: 'TOUCHPAD_MODE',
  GRID_SIZE: 'GRID_SIZE',
  TOUCHPAD_SENS: 'TOUCHPAD_SENS',

  // Sticks
  STICK_DEADZONE_INNER: 'STICK_DEADZONE_INNER',
  STICK_DEADZONE_OUTER: 'STICK_DEADZONE_OUTER',
  LEFT_STICK_DEADZONE_INNER: 'LEFT_STICK_DEADZONE_INNER',
  LEFT_STICK_DEADZONE_OUTER: 'LEFT_STICK_DEADZONE_OUTER',
  RIGHT_STICK_DEADZONE_INNER: 'RIGHT_STICK_DEADZONE_INNER',
  RIGHT_STICK_DEADZONE_OUTER: 'RIGHT_STICK_DEADZONE_OUTER',
  LEFT_STICK_MODE: 'LEFT_STICK_MODE',
  RIGHT_STICK_MODE: 'RIGHT_STICK_MODE',
  LEFT_RING_MODE: 'LEFT_RING_MODE',
  RIGHT_RING_MODE: 'RIGHT_RING_MODE',
  STICK_SENS: 'STICK_SENS',
  STICK_POWER: 'STICK_POWER',
  STICK_ACCELERATION_RATE: 'STICK_ACCELERATION_RATE',
  STICK_ACCELERATION_CAP: 'STICK_ACCELERATION_CAP',
  FLICK_TIME: 'FLICK_TIME',
  FLICK_TIME_EXPONENT: 'FLICK_TIME_EXPONENT',
  FLICK_SNAP_MODE: 'FLICK_SNAP_MODE',
  FLICK_SNAP_STRENGTH: 'FLICK_SNAP_STRENGTH',
  FLICK_DEADZONE_ANGLE: 'FLICK_DEADZONE_ANGLE',
  MOUSE_RING_RADIUS: 'MOUSE_RING_RADIUS',
  SCROLL_SENS: 'SCROLL_SENS',
  ADAPTIVE_TRIGGER: 'ADAPTIVE_TRIGGER',

  // Binding specials
  GYRO_OFF: 'GYRO_OFF',
  GYRO_ON: 'GYRO_ON',
  GYRO_OFF_ALL: 'GYRO_OFF_ALL',
  GYRO_ON_ALL: 'GYRO_ON_ALL',
  GYRO_INVERT: 'GYRO_INVERT',
  GYRO_INV_X: 'GYRO_INV_X',
  GYRO_INV_Y: 'GYRO_INV_Y',
  GYRO_TRACKBALL: 'GYRO_TRACKBALL',
  GYRO_TRACK_X: 'GYRO_TRACK_X',
  GYRO_TRACK_Y: 'GYRO_TRACK_Y',

  // Other
  TRACKBALL_DECAY: 'TRACKBALL_DECAY',
} as const
